enable-magisk-update = true
parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
arch = "both"
build-mode = "module"
included-patches = "'MaterialYou'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"

[Youtube-Music]
app-name = "Youtube Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
arch = "both"
build-mode = "module"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Dark theme'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
dpi = "120-640dpi"
build-mode = "module"
